# OC City Council Scrapers
#
# Each city has its own scraper in scrapers/cities/ with dynamic member discovery.
# All scrapers extend BaseScraper for consistent data extraction.

from .base import BaseScraper

# Import all city scrapers from the cities subpackage
from .cities import (
    AlisoViejoScraper,
    AnaheimScraper,
    BreaScraper,
    BuenaParkScraper,
    CostaMesaScraper,
    CypressScraper,
    DanaPointScraper,
    FountainValleyScraper,
    FullertonScraper,
    GardenGroveScraper,
    HuntingtonBeachScraper,
    IrvineScraper,
    LaHabraScraper,
    LaPalmaScraper,
    LagunaBeachScraper,
    LagunaHillsScraper,
    LagunaNiguelScraper,
    LagunaWoodsScraper,
    LakeForestScraper,
    LosAlamitosScraper,
    MissionViejoScraper,
    NewportBeachScraper,
    OrangeScraper,
    PlacentiaScraper,
    RanchoSantaMargaritaScraper,
    SanClementeScraper,
    SanJuanCapistranoScraper,
    SantaAnaScraper,
    SealBeachScraper,
    StantonScraper,
    TustinScraper,
    VillaParkScraper,
    WestminsterScraper,
    YorbaLindaScraper,
)

# Registry of all scrapers by city name
SCRAPERS = {
    "Aliso Viejo": AlisoViejoScraper,
    "Anaheim": AnaheimScraper,
    "Brea": BreaScraper,
    "Buena Park": BuenaParkScraper,
    "Costa Mesa": CostaMesaScraper,
    "Cypress": CypressScraper,
    "Dana Point": DanaPointScraper,
    "Fountain Valley": FountainValleyScraper,
    "Fullerton": FullertonScraper,
    "Garden Grove": GardenGroveScraper,
    "Huntington Beach": HuntingtonBeachScraper,
    "Irvine": IrvineScraper,
    "La Habra": LaHabraScraper,
    "La Palma": LaPalmaScraper,
    "Laguna Beach": LagunaBeachScraper,
    "Laguna Hills": LagunaHillsScraper,
    "Laguna Niguel": LagunaNiguelScraper,
    "Laguna Woods": LagunaWoodsScraper,
    "Lake Forest": LakeForestScraper,
    "Los Alamitos": LosAlamitosScraper,
    "Mission Viejo": MissionViejoScraper,
    "Newport Beach": NewportBeachScraper,
    "Orange": OrangeScraper,
    "Placentia": PlacentiaScraper,
    "Rancho Santa Margarita": RanchoSantaMargaritaScraper,
    "San Clemente": SanClementeScraper,
    "San Juan Capistrano": SanJuanCapistranoScraper,
    "Santa Ana": SantaAnaScraper,
    "Seal Beach": SealBeachScraper,
    "Stanton": StantonScraper,
    "Tustin": TustinScraper,
    "Villa Park": VillaParkScraper,
    "Westminster": WestminsterScraper,
    "Yorba Linda": YorbaLindaScraper,
}

__all__ = [
    "BaseScraper",
    "SCRAPERS",
    "AlisoViejoScraper",
    "AnaheimScraper",
    "BreaScraper",
    "BuenaParkScraper",
    "CostaMesaScraper",
    "CypressScraper",
    "DanaPointScraper",
    "FountainValleyScraper",
    "FullertonScraper",
    "GardenGroveScraper",
    "HuntingtonBeachScraper",
    "IrvineScraper",
    "LaHabraScraper",
    "LaPalmaScraper",
    "LagunaBeachScraper",
    "LagunaHillsScraper",
    "LagunaNiguelScraper",
    "LagunaWoodsScraper",
    "LakeForestScraper",
    "LosAlamitosScraper",
    "MissionViejoScraper",
    "NewportBeachScraper",
    "OrangeScraper",
    "PlacentiaScraper",
    "RanchoSantaMargaritaScraper",
    "SanClementeScraper",
    "SanJuanCapistranoScraper",
    "SantaAnaScraper",
    "SealBeachScraper",
    "StantonScraper",
    "TustinScraper",
    "VillaParkScraper",
    "WestminsterScraper",
    "YorbaLindaScraper",
]
